global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orderservice'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:7084'] 