apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orderservice-ingress
  annotations:
    # ISPRAVAK: Koristimo novi, moderni ingress class za Application Routing
    kubernetes.io/ingress.class: "webapp/routing"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orderservice-service
            port:
              number: 80