apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
      - name: inventoryservice
        image: __ACR_NAME__.azurecr.io/inventoryservice:__IMAGE_TAG__
        ports:
        - containerPort: 8080