apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "showcase-kv-bm123"   # Ime vašeg Key Vaulta
    clientID: "bfdea1cb-4042-470d-aba5-40805a4350e1" # Client ID vašeg Managed Identity-a
    tenantId: "cb71c4a1-79d3-4ed7-b9a3-18b3592d71c8" # ID vašeg tenanta
    objects: |
      array:
        - |
          objectName: sql-connection-string
          objectType: secret