apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "showcase-kv-bm123" # Zamijenite s imenom vašeg Key Vaulta
    clientID: "__IDENTITY_CLIENT_ID__" # NOVI PLACEHOLDER
    tenantId: "cb71c4a1-79d3-4ed7-b9a3-18b3592d71c8" # Zamijenite s ID-em vašeg tenanta
    objects: |
      array:
        - |
          objectName: sql-connection-string
          objectType: secret