apiVersion: v1
kind: Service
metadata:
  name: orderservice-service
spec:
  # ISPRAVAK: Mijenjamo tip servisa u LoadBalancer.
  # Ovo će automatski kreirati javni Load Balancer na Azureu i dodijeliti mu IP adresu.
  type: LoadBalancer 
  selector:
    app: orderservice
  ports:
  - port: 80
    targetPort: 8080