name: Build and Deploy to Azure AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: showcaseacrbm123 # OBAVEZNO: Zamijenite s imenom vašeg ACR-a
  RESOURCE_GROUP: AzureShowcase-RG
  AKS_CLUSTER_NAME: showcase-aks-cluster

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push OrderService
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/orderservice:${{ github.sha }} -f ./src/OrderService/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/orderservice:${{ github.sha }}
          
      - name: Build and push InventoryService
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/inventoryservice:${{ github.sha }} -f ./src/InventoryService/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/inventoryservice:${{ github.sha }}

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Replace placeholders in Kubernetes manifests
        run: |
          sed -i 's|__ACR_NAME__|${{ env.ACR_NAME }}|g' ./k8s/deployment.yml
          sed -i 's|__IMAGE_TAG__|${{ github.sha }}|g' ./k8s/deployment.yml
          sed -i 's|__ACR_NAME__|${{ env.ACR_NAME }}|g' ./k8s/inventory-deployment.yml
          sed -i 's|__IMAGE_TAG__|${{ github.sha }}|g' ./k8s/inventory-deployment.yml

      - name: Deploy to AKS with Retry
        run: |
          # FINALNI ISPRAVAK: Koristimo petlju za ponovne pokušaje
          # Ovo rješava "race condition" gdje CRD još nije spreman.
          
          echo "Pokušavam primijeniti SecretProviderClass..."
          for i in {1..5}; do
            kubectl apply -f ./k8s/secret-provider.yml && break
            echo "Čekam da SecretProviderClass CRD bude dostupan... (Pokušaj $i od 5)"
            sleep 20
          done
          
          # Finalna provjera - ako i dalje ne uspije, workflow će pasti s jasnom greškom
          kubectl apply -f ./k8s/secret-provider.yml
          
          echo "SecretProviderClass uspješno primijenjen. Nastavljam s ostatkom deploymenta..."
          
          # Primjenjujemo ostatak manifesta
          kubectl apply -f ./k8s/deployment.yml
          kubectl apply -f ./k8s/service.yml
          kubectl apply -f ./k8s/inventory-deployment.yml
          kubectl apply -f ./k8s/inventory-service.yml